name: My First Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run script
        run: |
          COUNT=$(find . -type f -not -path './.git/*' | wc -l)
          echo "Hello, your file count is $COUNT"